# Create a mapping dictionary for country names
country_mapping = {
    "USA": "United States",
    "turkey": "Türkiye",
    "Lebanon (Middle East)": "Lebanon",
    "On the way to Cozumel": "Mexico",
    "South-Africa": "South Africa",
    "Macedonia": "North Macedonia",
    "Trinidad/Tobago": "Trinidad and Tobago",
    "Luxemburg": "Luxembourg",
    "East China Sea": "China",
    "Iran": "Iran",
    "Decalb": "United States",
    "Turkey": "Türkiye",
    "South Korea": "South Korea",
    "North Wales": "United Kingdom",
    "Srui Lanka": "Sri Lanka",
    "Taiwan": "Taiwan",
    "Venezuela": "Venezuela",
    "South Georgia and the south sandwich islands": "South Georgia and the South Sandwich Islands",
    "Western Australia": "Australia",
    "Hellenic Republic": "Greece",
    "Portereco 2 miles of the coast": "Puerto Rico",
    "Republic of Ireland": "Ireland",
    "Republic of South Africa": "South Africa",
    "Tenerife, Spain": "Spain",
    "Puerto rico": "Puerto Rico",
    "Scotland": "United Kingdom",
    "Czech Republic": "Czechia",
    "Bolivia": "Bolivia",
    "Russia (former Ukraine)": "Russia",
    "Isle of Man, Great Britain": "Isle of Man",
    "South Korea / Japan": "South Korea",
    "canada": "Canada",
    "OMAN/UAE": "Oman",
    "Brunei": "Brunei",
    "italy": "Italy",
    "Caicos Islands": "Turks and Caicos Islands",
    "Quebec": "Canada",
    "United States": "United States",
    "Grand Canary Island": "Spain",
    "London": "United Kingdom",
    "St Thomas and Nassau": "Bahamas",
    "Over ocean between London and Northern Netherlands": "Netherlands",
    "U. S. Virgin Islands": "United States Virgin Islands",
    "Dominica, West Indies": "Dominica",
    "Nigeria 🇳🇬": "Nigeria",
    "Northern Ireland": "United Kingdom",
    "Russia": "Russia",
    "Puerto Rico Commonwealth": "Puerto Rico",
    "Hong Kong S.A.R.": "Hong Kong",
    "hatton city, Sri Lanka": "Sri Lanka",
    "non applicable": None,
    "Kosovo": "Kosovo",
    "Regatul Unit": "United Kingdom",
    "Menorca": "Spain",
    "Curacao": "Curaçao",
    "British Virgin Islands": "British Virgin Islands",
    "Sukumwit": None,
    "Caribbean (Grand Turk)": "Turks and Caicos Islands",
    "South  Africa": "South Africa",
    "US and Canada Border": "United States",
    "US Virgin Islands": "United States Virgin Islands",
    "Israel\\occupied palestine": "Israel",
    "Saipan": "Northern Mariana Islands",
    "Santo Domingo": "Dominican Republic",
    "usa": "United States",
    "Roma": "Italy",
    "Chennai. Tamil Nadu": "India",
    "india": "India",
    "Tanzania": "Tanzania",
    "Bosnia and herzegovina": "Bosnia and Herzegovina",
    "Tenerife": "Spain",
    "USAUSA": "United States",
    "Dublin Ireland": "Ireland",
    "Grenoble": "France",
    "Italy/Greece": "Italy",
    "mexico": "Mexico",
    "Hong Kong SAR": "Hong Kong",
    "UK/England": "United Kingdom",
    "Nederland": "Netherlands",
    "Republic of Panama": "Panama",
    "Macedonia (FYROM)": "North Macedonia",
    "south africa": "South Africa",
    "Citizen": None,
    "Murcia": "Spain",
    "The Bahamas": "Bahamas",
    "Antigua": "Antigua and Barbuda",
    "Slovak Republic": "Slovakia",
    "United Arad Emirates": "United Arab Emirates",
    "Norge": "Norway",
    "St. Kitts": "Saint Kitts and Nevis",
    "Syria": "Syria",
    "Korea (South)": "South Korea",
    "Trinidad": "Trinidad and Tobago",
    "Cuba/Florida (between)": "United States",
    "Netherlands Antilles": "Netherlands",
    "Sultanate of Oman": "Oman",
    "united kingdom": "United Kingdom",
    "Serbia and Montenegro": "Serbia",
    "Mediterranean sea.": "Mediterranean Sea",
    "Bahamas The": "Bahamas",
    "Tijuana b.c": "Mexico",
    "USAv": "United States",
    "UAE": "United Arab Emirates",
    "Vietnam": "Vietnam",
    "U.S.A.": "United States",
    "Reunion Island": "Réunion",
    "Corsica (France)": "France",
    "North Atlantic": "Atlantic Ocean",
    "Andaman Islands": "India",
    "Perú": "Peru",
    "Virgin Islands": "United States Virgin Islands",
    "Korea South": "South Korea",
    "Grand Cayman": "Cayman Islands",
    "Thailand & Malaysia": "Thailand",
    "Kyrgyzistan": "Kyrgyzstan",
    "French West Indies": "France",
    "Republic of Macedonia": "North Macedonia",
    "Pacific Ocean ( between Philippines and Japan )": "Pacific Ocean",
    "Mediterranean Sea": "Mediterranean Sea",
    "Bahamas/USA": "Bahamas",
    "Saint Helena South Atlantic Ocean": "Saint Helena",
    "Indian Ocean": "Indian Ocean",
    "Gran Canaria": "Spain",
    "Crete (Greece)": "Greece",
    "Oakland": "United States",
    "Corsica": "France",
    "ITALY": "Italy",
    "Aegean Sea": "Greece",
    "Indian Ocean 500 miles from nearest land": "Indian Ocean",
    "USVI": "United States Virgin Islands",
    "Trinidad & Tobago": "Trinidad and Tobago",
    "Okinawa": "Japan",
    "Europe": "Europe",
    "Usa": "United States",
    "Persian Gulf": "Persian Gulf",
    "East Atlantic Ocean": "Atlantic Ocean",
    "Swizterland": "Switzerland",
    "China Also?": "China",
    "Saint Maarten": "Sint Maarten",
    "Northern Cyprus": "Cyprus",
    "Korea": "South Korea",
    "St. Lucia": "Saint Lucia",
    "Japan (Okinawa)": "Japan",
    "West Germany": "Germany",
    "Caribbean Sea/Atantic Ocean": "Caribbean Sea",
    "Virgin Islands (U. S.)": "United States Virgin Islands",
    "Germany/Holland": "Germany",
    "North Atlantic Ocean": "Atlantic Ocean",
    "Turks & Caicos": "Turks and Caicos Islands",
    "Kingdom of Bahrain": "Bahrain",
    "Panama Canal": "Panama",
    "Puerto Rico/Burmuda (between)": "Puerto Rico",
    "North Sea": "North Sea",
    "Kenya (East Africa)": "Kenya",
    "PUERTO RICO": "Puerto Rico",
    "Foreign": None,
    "Okinawa Japan": "Japan",
    "Croatia (Hrvatska)": "Croatia",
    "Caribbean": "Caribbean",
}
